import { Router } from "express";
import { withCommand } from "@app/base/command.middleware";
import { ManagerWorkspaceAdminController } from "./admin.manager-workspace.controller";

export function adminManagerWorkspaceRoutes(
  controller: ManagerWorkspaceAdminController,
): Router {
  const router = Router();

  router.get(
    "/context",
    withCommand("MANAGER_WORKSPACE_CONTEXT"),
    controller.execute,
  );
  router.get(
    "/groups",
    withCommand("MANAGER_WORKSPACE_LIST_GROUPS"),
    controller.execute,
  );
  router.get(
    "/groups/:scopeType/:scopeId",
    withCommand("MANAGER_WORKSPACE_GET_GROUP"),
    controller.execute,
  );
  router.get(
    "/groups/:scopeType/:scopeId/members",
    withCommand("MANAGER_WORKSPACE_LIST_MEMBERS"),
    controller.execute,
  );
  router.get(
    "/groups/:scopeType/:scopeId/members/:memberId",
    withCommand("MANAGER_WORKSPACE_GET_MEMBER"),
    controller.execute,
  );
  router.get(
    "/events",
    withCommand("MANAGER_WORKSPACE_LIST_EVENTS"),
    controller.execute,
  );
  router.get(
    "/events/:eventId",
    withCommand("MANAGER_WORKSPACE_GET_EVENT"),
    controller.execute,
  );
  router.get(
    "/revenue/platform-earning-scope",
    withCommand("MANAGER_WORKSPACE_REVENUE_PLATFORM_EARNING_SCOPE"),
    controller.execute,
  );
  router.get(
    "/revenue/platform-earning-batches",
    withCommand("MANAGER_WORKSPACE_LIST_REVENUE_PLATFORM_EARNING_BATCHES"),
    controller.execute,
  );
  router.get(
    "/revenue/platform-earning-batches/:batchId",
    withCommand("MANAGER_WORKSPACE_GET_REVENUE_PLATFORM_EARNING_BATCH"),
    controller.execute,
  );
  router.get(
    "/revenue/platform-earning-batches/:batchId/source-lines",
    withCommand("MANAGER_WORKSPACE_LIST_REVENUE_PLATFORM_EARNING_LINES"),
    controller.execute,
  );
  router.get(
    "/work-schedule/work-shifts",
    withCommand("MANAGER_WORKSPACE_LIST_WORK_SHIFTS"),
    controller.execute,
  );
  router.get(
    "/work-schedule/weekly-schedule",
    withCommand("MANAGER_WORKSPACE_GET_WEEKLY_SCHEDULE"),
    controller.execute,
  );
  router.get(
    "/work-schedule/availability-members",
    withCommand("MANAGER_WORKSPACE_LIST_WORK_SCHEDULE_AVAILABILITY_MEMBERS"),
    controller.execute,
  );
  router.get(
    "/work-schedule/request-batches",
    withCommand("MANAGER_WORKSPACE_LIST_WORK_SCHEDULE_REQUEST_BATCHES"),
    controller.execute,
  );
  router.post(
    "/work-schedule/request-batches",
    withCommand("MANAGER_WORKSPACE_SUBMIT_WORK_SCHEDULE_REQUEST_BATCH"),
    controller.execute,
  );
  router.get(
    "/work-schedule/request-batches/:batchId",
    withCommand("MANAGER_WORKSPACE_GET_WORK_SCHEDULE_REQUEST_BATCH"),
    controller.execute,
  );
  router.post(
    "/work-schedule/request-batches/:batchId/cancel",
    withCommand("MANAGER_WORKSPACE_CANCEL_WORK_SCHEDULE_REQUEST_BATCH"),
    controller.execute,
  );
  router.post(
    "/work-schedule/request-batches/:batchId/lines/:lineId/cancel",
    withCommand("MANAGER_WORKSPACE_CANCEL_WORK_SCHEDULE_REQUEST_LINE"),
    controller.execute,
  );
  router.get(
    "/work-schedule/availability-batches",
    withCommand("MANAGER_WORKSPACE_LIST_WORK_SCHEDULE_AVAILABILITY_BATCHES"),
    controller.execute,
  );
  router.post(
    "/work-schedule/availability-batches",
    withCommand("MANAGER_WORKSPACE_SUBMIT_WORK_SCHEDULE_AVAILABILITY_BATCH"),
    controller.execute,
  );
  router.get(
    "/work-schedule/availability-batches/:batchId",
    withCommand("MANAGER_WORKSPACE_GET_WORK_SCHEDULE_AVAILABILITY_BATCH"),
    controller.execute,
  );
  router.post(
    "/work-schedule/availability-batches/:batchId/cancel",
    withCommand("MANAGER_WORKSPACE_CANCEL_WORK_SCHEDULE_AVAILABILITY_BATCH"),
    controller.execute,
  );
  router.post(
    "/work-schedule/availability-batches/:batchId/lines/:lineId/cancel",
    withCommand("MANAGER_WORKSPACE_CANCEL_WORK_SCHEDULE_AVAILABILITY_LINE"),
    controller.execute,
  );

  return router;
}
