import { Router } from "express";
import { withCommand } from "@app/base/command.middleware";
import { ManagerWorkspaceAdminController } from "./admin.manager-workspace.controller";

export function adminManagerWorkspaceRoutes(
  controller: ManagerWorkspaceAdminController,
): Router {
  const router = Router();

  router.get(
    "/context",
    withCommand("MANAGER_WORKSPACE_CONTEXT"),
    controller.execute,
  );
  router.get(
    "/events",
    withCommand("MANAGER_WORKSPACE_LIST_EVENTS"),
    controller.execute,
  );
  router.get(
    "/events/:eventId",
    withCommand("MANAGER_WORKSPACE_GET_EVENT"),
    controller.execute,
  );
  router.get(
    "/revenue/platform-earning-scope",
    withCommand("MANAGER_WORKSPACE_REVENUE_PLATFORM_EARNING_SCOPE"),
    controller.execute,
  );
  router.get(
    "/revenue/platform-earning-batches",
    withCommand("MANAGER_WORKSPACE_LIST_REVENUE_PLATFORM_EARNING_BATCHES"),
    controller.execute,
  );
  router.post(
    "/revenue/platform-earning-batches",
    withCommand("MANAGER_WORKSPACE_CREATE_REVENUE_PLATFORM_EARNING_BATCH"),
    controller.execute,
  );
  router.get(
    "/revenue/platform-earning-batches/:batchId",
    withCommand("MANAGER_WORKSPACE_GET_REVENUE_PLATFORM_EARNING_BATCH"),
    controller.execute,
  );
  router.patch(
    "/revenue/platform-earning-batches/:batchId",
    withCommand("MANAGER_WORKSPACE_UPDATE_REVENUE_PLATFORM_EARNING_BATCH"),
    controller.execute,
  );
  router.get(
    "/revenue/platform-earning-batches/:batchId/source-lines",
    withCommand("MANAGER_WORKSPACE_LIST_REVENUE_PLATFORM_EARNING_LINES"),
    controller.execute,
  );
  router.post(
    "/revenue/platform-earning-batches/:batchId/source-lines",
    withCommand("MANAGER_WORKSPACE_ADD_REVENUE_PLATFORM_EARNING_LINE"),
    controller.execute,
  );
  router.patch(
    "/revenue/platform-earning-batches/:batchId/source-lines/:lineId",
    withCommand("MANAGER_WORKSPACE_UPDATE_REVENUE_PLATFORM_EARNING_LINE"),
    controller.execute,
  );
  router.post(
    "/revenue/platform-earning-batches/:batchId/submit",
    withCommand("MANAGER_WORKSPACE_SUBMIT_REVENUE_PLATFORM_EARNING_BATCH"),
    controller.execute,
  );
  router.get(
    "/work-schedule/work-shifts",
    withCommand("MANAGER_WORKSPACE_LIST_WORK_SHIFTS"),
    controller.execute,
  );
  router.get(
    "/work-schedule/availability-members",
    withCommand(
      "MANAGER_WORKSPACE_LIST_WORK_SCHEDULE_AVAILABILITY_MEMBERS",
    ),
    controller.execute,
  );
  router.get(
    "/work-schedule/request-batches",
    withCommand(
      "MANAGER_WORKSPACE_LIST_WORK_SCHEDULE_REQUEST_BATCHES",
    ),
    controller.execute,
  );
  router.post(
    "/work-schedule/request-batches",
    withCommand(
      "MANAGER_WORKSPACE_SUBMIT_WORK_SCHEDULE_REQUEST_BATCH",
    ),
    controller.execute,
  );
  router.get(
    "/work-schedule/request-batches/:batchId",
    withCommand(
      "MANAGER_WORKSPACE_GET_WORK_SCHEDULE_REQUEST_BATCH",
    ),
    controller.execute,
  );
  router.post(
    "/work-schedule/request-batches/:batchId/cancel",
    withCommand(
      "MANAGER_WORKSPACE_CANCEL_WORK_SCHEDULE_REQUEST_BATCH",
    ),
    controller.execute,
  );
  router.post(
    "/work-schedule/request-batches/:batchId/lines/:lineId/cancel",
    withCommand(
      "MANAGER_WORKSPACE_CANCEL_WORK_SCHEDULE_REQUEST_LINE",
    ),
    controller.execute,
  );
  router.get(
    "/work-schedule/availability-batches",
    withCommand(
      "MANAGER_WORKSPACE_LIST_WORK_SCHEDULE_AVAILABILITY_BATCHES",
    ),
    controller.execute,
  );
  router.post(
    "/work-schedule/availability-batches",
    withCommand(
      "MANAGER_WORKSPACE_SUBMIT_WORK_SCHEDULE_AVAILABILITY_BATCH",
    ),
    controller.execute,
  );
  router.get(
    "/work-schedule/availability-batches/:batchId",
    withCommand(
      "MANAGER_WORKSPACE_GET_WORK_SCHEDULE_AVAILABILITY_BATCH",
    ),
    controller.execute,
  );
  router.post(
    "/work-schedule/availability-batches/:batchId/cancel",
    withCommand(
      "MANAGER_WORKSPACE_CANCEL_WORK_SCHEDULE_AVAILABILITY_BATCH",
    ),
    controller.execute,
  );
  router.post(
    "/work-schedule/availability-batches/:batchId/lines/:lineId/cancel",
    withCommand(
      "MANAGER_WORKSPACE_CANCEL_WORK_SCHEDULE_AVAILABILITY_LINE",
    ),
    controller.execute,
  );

  return router;
}
